name: Baseline

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: check pwd
        run: |
          pwd
      - name: Run ZAP Baseline Scan
        run: |
          docker run --user root \
            -v zap:/zap/wrk/:rw \
            -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://www.scientificamerican.com -g /zap/wrk/gen.conf -r /zap/wrk/testreport.html

      - name: List Files in Working Directory
        run: ls -l

      - name: Upload ZAP Report and Config as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Scan-Results
          path: |
            gen.conf
            testreport.html
