name: Config

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZAP Baseline Scan
        continue-on-error: true
        run: |
          docker run -v zap:/zap/wrk/:rw -t ghcr.io/zaproxy/zaproxy:stable \
          zap-baseline.py -t https://www.scientificamerican.com -g baseline.conf -r testreport.html

      - name: Upload ZAP Baseline Config
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-config
          path: zap/baseline.conf

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-Report
          path: zap/zap_report.html
