name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up baseline.conf
        run: |
          mkdir -p /home/zap
          rm -rf /home/zap/baseline.conf  # Ensure it's not a directory
          cat <<EOF > /home/zap/baseline.conf
          target=https://scientificamerican.com
          format=html
          output=zap_report.html
          minLevel=Low
          reportTitle=ZAP Security Scan Report
          contextFile=zap_context.context
          EOF
          cat /home/zap/baseline.conf  # Verify contents

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v "/home/zap/baseline.conf:/home/zap/baseline.conf" \
            -v "$PWD:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /home/zap/baseline.conf

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
