name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up workspace and ensure `baseline.conf` exists
        run: |
          mkdir -p $GITHUB_WORKSPACE/zap
          echo "# ZAP Baseline Scan Configuration" > $GITHUB_WORKSPACE/zap/baseline.conf
          echo "ignore-alerts=None" >> $GITHUB_WORKSPACE/zap/baseline.conf
          echo "max-duration=600" >> $GITHUB_WORKSPACE/zap/baseline.conf
          echo "context=None" >> $GITHUB_WORKSPACE/zap/baseline.conf

      - name: Verify directory structure
        run: tree $GITHUB_WORKSPACE

      - name: Check if `baseline.conf` is present
        run: ls -lah $GITHUB_WORKSPACE/zap

      - name: Run ZAP Baseline Scan test
        run: |
            docker run --rm \
            -v "$(pwd)/baseline.conf:/home/zap/baseline.conf" \
            -v "$(pwd)/zap_report.html:/home/zap/zap_report.html" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /home/zap/baseline.conf
        



      # - name: Run ZAP Baseline Scan
      #   run: |
      #     docker run --rm ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t https://www.scientificamerican.com -d
          
      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap/testreport.html
