name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create baseline.conf (Automation Plan)
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/baseline.conf
          env:
            contexts:
              - name: "Test Context"
                urls:
                  - "https://scientificamerican.com"
          jobs:
            - type: "spider"
              parameters:
                context: "Test Context"
            - type: "passiveScan-config"
              parameters:
                maxAlertsPerRule: 10
            - type: "report"
              parameters:
                format: "html"
                template: "traditional-html"
                reportTitle: "ZAP Security Scan Report"
                reportDescription: "ZAP automated security scan report."
                filename: "/zap/wrk/zap_report.html"
          EOF
          cat $GITHUB_WORKSPACE/baseline.conf  # Verify the file contents



      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE/baseline.conf:/zap/baseline.conf" \
            -v "$GITHUB_WORKSPACE:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /zap/baseline.conf

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/zap_report.html
