name: ZAP Baseline Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up workspace
        run: |
          mkdir -p $GITHUB_WORKSPACE/zap
          touch $GITHUB_WORKSPACE/zap/baseline.conf

      - name: Verify directory structure
        run: ls -lah $GITHUB_WORKSPACE/zap

      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE/zap:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t https://www.scientificamerican.com \
            -g /zap/wrk/baseline.conf -r /zap/wrk/testreport.html

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: zap/testreport.html
