name: ZAP Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create baseline.conf
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/baseline.conf
          {
            "target": "https://scientificamerican.com",
            "format": "html",
            "output": "zap_report.html",
            "minLevel": "Low",
            "reportTitle": "ZAP Security Scan Report",
            "contextFile": "zap_context.context"
          }
          EOF
          cat $GITHUB_WORKSPACE/baseline.conf  # Verify contents


      - name: Run ZAP Baseline Scan
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE/baseline.conf:/zap/baseline.conf" \
            -v "$GITHUB_WORKSPACE:/zap/wrk" \
            ghcr.io/zaproxy/zaproxy:stable \
            zap.sh -cmd -autorun /zap/baseline.conf

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: $GITHUB_WORKSPACE/zap_report.html
